# --- !Ups

create table "blog" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "title" varchar not null,
  "content" varchar not null,
  "date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

create table "comment" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "id_blog" bigint not null,
  "name" varchar not null,
  "content" varchar not null,
  "date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
# --- !Downs

drop table "blog" if exists;
drop table "comment" if exists;